name: Deploy to Build Branch
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Deploy to Build Branch
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm install and build
      run: |
        npm install
        npm run build
      env:
        MODE: production

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: build
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
